spring.application.name=service-registry

server.port=8761

#Eureka server should noot register itslef as a client
# By default Eureka tries to rgister itslef - we diable that since this since this is a server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false