# kafka broker address
# bootstrap-servers - address of the kafka broker - only one needed
# kafka auto-dicovers the rest of the cluster from it
spring.application.name=springboot-kafka
spring.kafka.bootstrap-servers=localhost:9092

# producer config
# key-serializer - converts the message key (String) to byte before sendingto kafka
# value-serialzer - converts the message value (String) to bytes before sending to kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# consumer config
# auto-offset-reset=earliest
# when consumer starts fresh with no prior offset,
# read all messages from the beginning of the topic
# key-deserializer
# converts bytes to String key when reading from kafka
# JSON serializer/deserializer config
# Tell consumer to trust our Student class for JSON deserialization
# Why is trusted-packages needed?
# Security measure — prevents deserialization of unknown classes.
# Must explicitly whitelist your package.
spring.kafka.consumer.group-id=myGroup
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
