server.port=8081
spring.application.name=user-service

#register with Eureka server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# spring.config.import?
# tells spring boot where to fetch external config from
# config server runs on port 8888 by default
# optional: means app starts even if config server is down
spring.config.import=optional:configserver:http://localhost:8888