server.port=8082

spring.application.name=order-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Resilience4j Circuit Breaker config
# slidingWindowSize - monitors last 5 calls to decide circuit state
resilience4j.circuitbreaker.instances.restaurantService.sliding-window-size=5

# failureRateThreshold - if 50% of last 5 calls fail -> circuit OPENS
resilience4j.circuitbreaker.instances.restaurantService.failure-rate-threshold=50

# waitDurationInOpenState - circuit stays OPEN for 10s before going HALF-OPEN to test recovery
resilience4j.circuitbreaker.instances.restaurantService.wait-duration-in-open-state=10s

# test calls allowed in HALF-OPEN
resilience4j.circuitbreaker.instances.restaurantService.permitted-number-of-calls-in-half-open-state=3

# show circuit breaker state in /actuator/health
resilience4j.circuitbreaker.instances.restaurantService.register-health-indicator=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
