server.port=8888
spring.application.name=config-server

# Where does Config Server read config files from?
# From a Git repo - local or remote GitHub
# spring.cloud.config.server.git.uri points to that repo
spring.cloud.config.server.git.uri=https://github.com/sristi-i/microservices-config
spring.cloud.config.server.git.clone-on-start=true